export const FETCH_LOCATIONS_PENDING = "FETCH_LOCATIONS_PENDING";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";
export const RESET_LOCATIONS ="RESET_LOCATIONS"
