export const FETCH_TRIP_SEARCH_PENDING = "FETCH_TRIP_SEARCH_PENDING";
export const FETCH_TRIP_SEARCH_SUCCESS = "FETCH_TRIP_SEARCH_SUCCESS";
export const FETCH_TRIP_SEARCH_FAILURE = "FETCH_TRIP_SEARCH_FAILURE";
